### ISSUE TITLE
Better Examples

### ISSUE THREAD

**Issue by jantimon** [webpack/mocha-loader#15]
Could you please provide a node and a web example?
It's hard to guess how this might work with the minimalistic readme.

This gist from #5 works quite well for web: 
https://gist.github.com/ampedandwired/ffee80734382123a3b14

however when running it with `target: 'node'` it does not work:

```bash
webpack

    Hash: 564c4a83ce6fdef7d115
    Version: webpack 1.7.3
    Time: 514ms
             Asset    Size  Chunks             Chunk Names
    test_bundle.js  150 kB       0  [emitted]  main
       [0] multi main 40 bytes {0} [built]
        + 17 hidden modules

    WARNING in ./~/mocha-loader/EnhancedMocha.js
    Critical dependencies:
    29:24-37 the request of a dependency is an expression
     @ ./~/mocha-loader/EnhancedMocha.js 29:24-37

    WARNING in ./~/mocha-loader/package.json
    Module parse failed: demo/node_modules/mocha-loader/package.json Line 2: Unexpected token :
    You may need an appropriate loader to handle this file type.
    | {
    |   "name": "mocha-loader",
    |   "version": "0.6.5",
    |   "author": {
     @ ./~/mocha-loader ^\.\/.*$

    WARNING in ./~/mocha-loader/README.md
    Module parse failed: demo/node_modules/mocha-loader/README.md Line 1: Unexpected token ILLEGAL
    You may need an appropriate loader to handle this file type.
    | # mocha loader for webpack
    | 
    | ## Usage
     @ ./~/mocha-loader ^\.\/.*$





node test_bundle.js 

    demo/test_bundle.js:138
    	module.exports = mocha;
    	                 ^
    ReferenceError: mocha is not defined
        at Object.map../EnhancedMocha (demo/test_bundle.js:138:19)
        at __webpack_require__ (demo/test_bundle.js:20:30)
        at Object.module.exports (demo/test_bundle.js:73:14)
        at __webpack_require__ (demo/test_bundle.js:20:30)
        at Object.<anonymous> (demo/test_bundle.js:55:22)
        at __webpack_require__ (demo/test_bundle.js:20:30)
        at Object.<anonymous> (demo/test_bundle.js:47:2)
        at __webpack_require__ (demo/test_bundle.js:20:30)
        at demo/test_bundle.js:40:18
        at Object.<anonymous> (demo/test_bundle.js:43:10)
```

**Comment by adamshone** [comment]
I'm having the same problem.

**Comment by levithomason** [comment]
I had this same issue.  Removing the `mocha-loader` when bundling for node seemed to work.

**Comment by tricoder42** [comment]
This can be resolved by adding `externals` option to webpack config. See related https://github.com/webpack/mocha-loader/issues/22#issuecomment-238820896

Feel free to reopen this issue if it doesn't solve your problem
